apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      securityContext:
        fsGroup: 2000 
      containers:
      - name: quiz-app-api
        image: lelayj/quiz-app-api:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000