version: '2'
services:
    tp5-mysql:
        container_name: tp5-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/tp5/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=tp5
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
